version: '2'
services:
  php_core:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /var/www
    container_name: php_core
    volumes:
      - ./src:/var/www
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/upload.ini:/usr/local/etc/php/conf.d/upload.ini
    links:
      - database
    environment:
      - "DB_HOST=database"
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    working_dir: /var/www
    container_name: php_core_web
    volumes:
      - ./docker/web/vhost.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php_core
    ports:
      - 8080:80
  database:
    platform: linux/x86_64
    build:
      context: ./docker/mysql_data
      dockerfile: Dockerfile
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
    container_name: php_core_database
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-mysql}
      - MYSQL_USER=${DB_USERNAME:-root}
      - MYSQL_PASSWORD=${DB_PASSWORD:-root}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-root}
    ports:
      - "3309:3306"
